spring:
  application:
    name: pre-test
  r2dbc:
    url: r2dbc:h2:file:///./data/testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: user
    password: user
  datasource:
    url: jdbc:h2:file:./data/testdb
    username: user
    password: user
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/init.sql

h2:
  console:
    port: 8090

api:
  sale:
    csv:
      uri: https://www.ftc.go.kr/www/downloadBizComm.do?atchFileUrl=dataopen&atchFileNm=
    detail:
      base-url: http://apis.data.go.kr/1130000/MllBsDtl_2Service
      uri: /getMllBsInfoDetail_2
      key: qv1kyws9BkH0nKIjJRiLZgLGfbER0sA388f3F7byLVvWKw+qzYrNwSWzsCh+I8KwgYirwTmfgm4R0bxsK2HyyA==
    address:
      base-url: https://business.juso.go.kr/addrlink
      uri: /addrLinkApi.do
      key: devU01TX0FVVEgyMDI1MDMyNTE1MTgxMTExNTU3NzE=
